config/routes.rb
Rails.application.routes.draw do

  get '/users/:id/confirm' => 'users#confirm', as: 'confirm'

 patch '/users/:id/confirms' => 'users#confirms', as: 'confirms'
devise_for :users
root to: 'homes#top'
   resources :users, only: [:show, :edit, :create, :index, :update, :destroy]
   resources :posts, only: [ :edit, :create, :index, :destroy]
   resources :comments, only: [:show, :index,:new, :create]
   resources :groups, only: [:create, :index, :destroy]
   resources :chats, only: [ :create, :index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
          has_many :comments, dependent: :destroy 
         
          
  def active_for_authentication?
    super && (is_deleted == true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :authenticate_user!, except: [:top,]
   before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
   comments_path
  end
  def after_sign_out_path_for(resource)
    root_path
    
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
  end

  def destroy
  end

  def create
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 def new
    @comments = Comment.new
 end
 
 def create
    @comments = Comment.new(comment_params)
    @comments.user_id = current_user.id
    @comments.save!
    redirect_to comments_path
 end
 def index
      @comments = Comment.all
 end

  def show
  end
  
  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  end

  def destroy
  end

  def create
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end
  
  def index
  end

  def edit
  end

  def create
  　post = Post.new(post_params)
  　post.save
    redirect_to comments_path
  end

  def destroy
  end
  
  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
     @user = User.find(params[:id])
        
  end

  def edit
     @user = User.find(params[:id])
  end

  def update
      @user = User.find(params[:id])
  if @user.update(user_params)
     flash[:notice] =  "You have updated user successfully."
     redirect_to user_path(@user.id)
  else
     render :edit
  end
  end

  def confirm
   @user = User.find(params[:id])
  end
  
  def confirms
   @user = User.find(params[:id])
  @user.update(is_deleted: false)
  reset_session
  flash[:notice] = "退会処理を実行いたしました"
  redirect_to root_path
  end
  
   def user_params
    params.require(:user).permit(:name, :introduction, :title, :boby)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/create.html.erb
<h1>Chats#create</h1>
<p>Find me in app/views/chats/create.html.erb</p>

app/views/chats/destroy.html.erb
<h1>Chats#destroy</h1>
<p>Find me in app/views/chats/destroy.html.erb</p>

app/views/chats/index.html.erb
<h1>Chats#index</h1>
<p>Find me in app/views/chats/index.html.erb</p>

app/views/comments/index.html.erb
<div class="container mt-2">

<%= flash[:notice] %>
<div class="col-md-8 offset-md-1">
<h1>投稿一覧</h1>
 <table class="table table-hover table-inverse">
  <thead>
  <tr>
  <th>name</th>
  <th>comment</th>
  </tr>
  </thead>
  <tbody>
  <% @comments.each do |comment| %>
   <tr>
    <td><%= comment.user.name %></td>
    <td><%= comment.comment %></td>
  </tr>
 <% end %>
  </tbody>
  </table>
  </div>
  </div>
  </div>

app/views/comments/new.html.erb
<div class="container mt-2">
<div class="mx-auto" style="width: 400px;">
<h1>コメント投稿画面</h1>
<%= form_with model: @comments do |f| %>
 
  <h4>comment</h4>
  <%= f.text_area :comment %>
  <%= f.submit '投稿' %>
<% end %>
</div>
</div>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/destroy.html.erb
<h1>Groups#destroy</h1>
<p>Find me in app/views/groups/destroy.html.erb</p>

app/views/groups/index.html.erb
<h1>Groups#index</h1>
<p>Find me in app/views/groups/index.html.erb</p>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8" />
    <script src="https://kit.fontawesome.com/db5b58bf59.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href=".css" />
</head>

<body>
 <header>
 </header>  
  <main>
  <div>
  <%= flash[:notice] %>
  </div>
  <div class="container">
  <div class="sidebar col-2">
  </div>
  <div class="col-lg-12">
  <div class="row">
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
  <h3>ライブ、フェスに一緒に行く人を探せるコミュニティサイトです！</h3>
  <div class="btn-wrapper col-10 mx-auto">
  <div class="row">
  <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
  </div>
  <div class="row">
  <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
  </div>
  </div>
  </div>
  </div>
  </div>
  </div>
  </main>
  <footer>
  </footer>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Livetogether</title>
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <script src="https://kit.fontawesome.com/db5b58bf59.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body class="d-flex flex-column vh-100">
    <header class="bg-dark text-white pt-3pb-4">
      <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
      <h5> <%= link_to 'livetogether', root_path, class: 'nav-link text-white'%> </h5>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarNavDropdown">
       <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
           <li class="nav-item">
           <%= link_to "ログアウト",destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>
           </li>
           <li class="nav-item">
           <%= link_to 'マイページ', user_path(current_user), class: 'nav-link text-white' %>
           </li>
             <li class="nav-item">
           <%= link_to 'コメント一覧', comments_path, class: 'nav-link text-white' %>
           </li>
           <li>
           <%= link_to '投稿フォーム', new_comment_path, class: 'nav-link text-white' %>
           </li>
          <% else %>
           <li class="nav-item">
           <%= link_to  "新規登録",new_user_registration_path, class: 'nav-link text-white' %>
           </li>
           <li class="nav-item">
           <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-white' %>
           </li>
          <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
    <%= yield %>
    </main>
     </body>
</html>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>コメント投稿</h1>
<%= form_with model: @post do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
	
  <h4>本文</h4>
  <%= f.text_area :text %>
	
  <%= f.submit '投稿' %>
<% end %>

app/views/users/confirm.html.erb
<div class="container mt-2">
<div class="mx-auto" style="width: 800px;">
  <h2>退会お手続き</h2> 
  <p>退会手続きをされますと、全てのサービスがご利用いただけなくなります。</br> 
    再度ご利用をいただく場合には、新規登録のお手続きが必要になります。</br> 
  </p>
    本当に退会してよろしいですか？
 <%= link_to "退会する", confirms_path, method: :patch, data: { confilm: "本当に退会しますか？" } %>
 <%= link_to "退会しない", root_path %>
 </div>
 </div>

app/views/users/edit.html.erb
 <div class="container mt-2">
<div class="mx-auto" style="width: 800px;">
<h2>プロフィール編集</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
 <label for="inputIntroduction">Introduction</label>
  <%= f.text_area :introduction, autofocus: true, id:"inputName", placeholder:"自己紹介"%>
  
  <%= f.submit "変更を保存" %>
<% end %>
</div>
 </div>

app/views/users/show.html.erb
 <div class="container mt-2">
 <div class="mx-auto" style="width: 600px;">

<table class="table">
     <tbody>
     <th>name</th>
     <th> <%= @user.name %> </tr>
     <th>introduction</th>
   　 <th><%= @user.introduction %> </th>
     </tbody>
     </table>
     <%= link_to "編集", edit_user_path(@user)  %>
　   <%= link_to "退会", confirm_path(@user) %>
 </div>
 </div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>